version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspace:cached
      - /var/run/docker.sock:/var/run/docker-host.sock
    command: sleep infinity
    environment:
      - PYTHONPATH=/workspace
      - DATA_PATH=/workspace/data
      - LOG_LEVEL=DEBUG
    networks:
      - devcontainer-network

  # Optional: Run Streamlit in development mode
  streamlit-dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspace:cached
    working_dir: /workspace
    command: streamlit run app/main.py --server.port=8501 --server.address=0.0.0.0 --server.runOnSave=true --server.fileWatcherType=poll
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/workspace
      - DATA_PATH=/workspace/data
      - LOG_LEVEL=DEBUG
    networks:
      - devcontainer-network
    profiles:
      - streamlit

networks:
  devcontainer-network:
    driver: bridge